---
baseurl: "/"
permalink: "/:title/"
title: Snipcart
snipcart_js: https://cdn.snipcart.com/themes/v3.0.4/default/snipcart.js
snipcart_css: https://cdn.snipcart.com/themes/v3.0.4/default/snipcart.css
snipcart_api_key: NjgzYTY0ZTctZmM0My00NjQ3LTg0MjYtMGNhYzUzMTM1ZDA0NjM3MTcxMDUzNTMyMjEwMDk2
logos:
  light:
    optimized: "/images/logo.webp"
    fallback: images/logo-white.svg
palette: default
palettes:
  default:
    sass:
      default: "#FFFFFF"
      light: "#F0F0F0"
      medium: "#6B797A"
      dark: "#384647"
      active: "#88DD9B"
      active_light: "#C0FDB6"
      active_medium: "#5C9174"
      active_dark: "#547567"
      dark_grey: "#273132"
      light_grey: "#6B797A"
      bg_image_primary_optimized: "/images/header.webp"
      bg_image_primary_fallback: "/images/promotion.jpg"
      bg_image_cart_optimized: "/images/cart-bg.webp"
      bg_image_cart_fallback: "/images/promotion.jpg"
sass:
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
collections:
  posts:
    permalink: "/posts/:title/"
